$(function(){function u(e,h,b){var c=$(this),d=$(document);c=c.parent();if(c.children(".uiBox").length)return false;c.parents(".postOption").find(".tipbox").remove();var a=$TAG("div",{cls:"uiBoxContent"}),f=$TAG("div",{cls:"uiBoxContainer"}).append(a),g=$TAG("div",{cls:"uiBox tipbox"}).append(f).css({width:h});a.append.apply(a,b);c.append(g);g.bgiframe();d.bind("click.ontit",function(i){if(!$(i.target).parents(e).length){g.remove();d.unbind(".ontit")}});return g}function B(e,h,b){var c=this,d=$(c).parents(".postForm"),
a=d.find(".publish_textarea"),f=a.val();if(f==""||d.find(".wordNumBg").hasClass("wordNumOver")){a.focus();WBP.noticeInput(a[0])}else{d=$TAG("button",{cls:"uiBtnp mrs"}).html("\u786e\u5b9a");var g=$TAG("button",{cls:"uiBtng"}).text("\u53d6\u6d88");d.click(function(){var j=a.data("img_id");$(c).attr("disabled",true).addClass("uiBtnLoading");i.close();$.ajax({url:b||"/app/postAjax/sendnow",type:"POST",dataType:"json",data:{content:f,image_id:j,id:e||0},success:function(k){$(c).attr("disabled",
false).removeClass("uiBtnLoading");if(parseInt(k.error))WBP.alertError(null,k.error_info);else if(h)h(k);else{a.val("").data("img","").data("img_id",0).addClass("post_success").keyup();setTimeout(function(){a.removeClass("post_success")},1500);$(".po_image .uiBox").remove();$(".precordGrid tr:eq(1)").after(k.data)}}})});g.click(function(){i.close()});d=$TAG("div",{cls:"pal clearfix"}).append($TAG("div",{cls:"lfloat confirmIco mrs"}),$TAG("div",{cls:"fcr fsl pvm"}).text("\u786e\u8ba4\u8981\u7acb\u5373\u53d1\u5e03\u5fae\u535a\u5417\uff1f"),
$TAG("div",{cls:"hRight"}).append(d,g));var i=new SGJ.BOX({loading:false,title:"\u7acb\u5373\u53d1\u5e03\uff1f",body:d,mask:BOXMASK});i.bgiframe()}}function C(e){var h=e.getFullYear(),b=e.getMonth()+1;e=e.getDate();return h+"-"+b+"-"+e}function v(e,h){for(var b=[],c=e;c<=h;c++){var d=c.toString();d=d.length==1?"0"+d:d;b.push(d)}return b}var p=window,w=function(){var e=$(this).parents(".postForm").find(".publish_textarea");App.showFaces(this,e[0],-29,5)},t=function(){var e=$(this).parent().parent(),
h=e.attr("target"),b=$(this).parents(".postForm"),c=b.find(".publish_textarea"),d=b.find(".postTimeBtn"),a=b.find(".postNowBtn");d.attr("disabled",true).addClass("uiBtnDisabled");a.attr("disabled",true).addClass("uiBtnDisabled");b=$TAG("div",{cls:"mask"});var f=$TAG("a",{cls:"uiClose"}).click(function(){n()}),g=$TAG("span",{cls:"vMiddle"}).text("\u4e0a\u4f20\u4e2d..."),i=$TAG("div",{cls:"mvl"}).append($TAG("img",{cls:"mrs vMiddle"}).attr("src","http://img.t.sinajs.cn/t3/style/images/common/loading.gif"),
g,f);f=$TAG("div",{cls:"uiBoxArrow"});var j=$TAG("div",{cls:"uiBoxContent hCent clearfix"}).append(b,f,i);b=$TAG("div",{cls:"uiBoxContainer"}).append(j);var k=$TAG("div",{cls:"uiBox"}).append(b).css({width:143});b=$TAG("input",{cls:"iptFile"}).attr({type:"file",name:"upload_pic"}).change(t);var n=function(){k.remove();c.data("img","");c.data("img_id",0);$iframe.remove()};$iframe=$('<iframe class="hidden" name="'+h+'" src="about:blank"></iframe>');$iframe.appendTo("body");e.submit();$(this).parents(".po_image").append(k);
$(this).after(b).remove();$EVENT($iframe[0],"load",function(){var q=eval("("+($iframe[0].contentDocument?$iframe[0].contentDocument:$iframe[0].contentWindow.document).body.innerHTML+")"),r=$TAG("a",{cls:"fcmb fsm mrs tinyico-del rfloat"}).text("\u5220\u9664").click(n);c.data("img",q.image);c.data("img_id",q.image_id);g.html("\u4e0a\u4f20\u5b8c\u6210<br>\u56fe\u7247\u8f7d\u5165\u4e2d...");d.attr("disabled",false).removeClass("uiBtnDisabled");a.attr("disabled",false).removeClass("uiBtnDisabled");var m=$TAG("img",{cls:"clear"}).attr("src",
q.image).width(120).height(120).load(function(){i.remove();j.append(r,m)});$iframe.remove()})},x=function(){var e=$(this).parents(".postForm").find(".publish_textarea"),h=$TAG("div",{cls:"uiBoxArrow"}),b=$TAG("a",{cls:"uiClose"}),c=$TAG("input",{cls:"pas fsl w250"}).attr("name","long_url"),d=$TAG("button",{cls:"uiBtng mls"}).attr({type:"button"}).html("<span>\u786e\u5b9a</span>"),a=$TAG("div",{cls:"pam fsm"}).append('<div class="mbs">\u8f93\u5165\u89c6\u9891\u7f51\u7ad9\u64ad\u653e\u9875\u94fe\u63a5\u5730\u5740</div>',
c,d,'<div class="mts fcg">\u76ee\u524d\u652f\u6301\u65b0\u6d6a\u64ad\u5ba2\u3001\u4f18\u9177\u7f51\u3001\u571f\u8c46\u7f51\u3001\u91776\u7f51\u300156\u7f51\u7b49\u7f51\u7ad9</div>'),f=u.call(this,".po_video",380,[h,b,a]);b.click(function(){f.remove()});d.click(function(){if($.browser.msie){var g=WBP.getCur(e[0]);WBP.setSelectText(e[0],g[0],g[1])}d.attr("disabled",true).addClass("uiBtnLoading");$.ajax({url:"/app/shortUrl",data:{long_url:c.val()},type:"POST",dataType:"json",success:function(i){i.short_url=
i.short_url||c.val();WBP.insertText(e[0],i.short_url+" ");e.keyup();f.remove()}});return false});return false},y=function(){var e=this,h=$(e).parents(".postForm").find(".publish_textarea"),b=$TAG("div",{cls:"uiBoxArrow"}),c=$TAG("a",{cls:"uiClose"}).click(function(){$(e).parents(".uiBox").remove()}),d=$TAG("input",{cls:"pas fsl w250"}).attr("name","long_url"),a=$TAG("button",{cls:"uiBtng mls"}).attr("type","submit").html("<span>\u786e\u5b9a</span>"),f=$TAG("div",{cls:"pam fsm"}).append('<div class="mbs">\u8f93\u5165\u5b8c\u6574\u7684\u97f3\u4e50\u94fe\u63a5\u5730\u5740</div>',
d,a),g=u.call(e,".po_music",380,[b,c,f]);c.click(function(){g.remove()});a.click(function(){if($.browser.msie){var i=WBP.getCur(h[0]);WBP.setSelectText(h[0],i[0],i[1])}a.attr("disabled",true).addClass("uiBtnLoading");$.ajax({url:"/app/shortUrl",data:{long_url:d.val()},type:"POST",dataType:"json",success:function(j){j.short_url=j.short_url||d.val();WBP.insertText(h[0],j.short_url+" ");h.keyup();g.remove()}});return false});return false},z=function(){var e=$(this).parents(".postForm").find(".publish_textarea");
WBP.insertTopic(e[0]);e.keyup();return false},A=function(e,h){var b=this,c=$(b).parents(".postForm"),d=c.find(".publish_textarea"),a=d.val(),f=d.data("img_id");if(a==""||c.find(".wordNumBg").hasClass("wordNumOver")){d.focus();WBP.noticeInput(d[0])}else{var g=c.find("[name=date]"),i=c.find("[name=hour]");c=c.find("[name=minute]");g=g.val();i=i.val();c=c.val();if(WBP.validatePostTime(g,i,c)){$(b).attr("disabled",true).addClass("uiBtnLoading");$.ajax({url:"/app/postAjax/update",type:"POST",dataType:"json",
data:{content:a,image_id:f,schedule_ymd:g,schedule_hour:i,schedule_minute:c,id:e||0},success:function(j){$(b).attr("disabled",false).removeClass("uiBtnLoading");if(parseInt(j.error))WBP.alertError(null,j.error_info);else if(h)h(j);else{d.val("").data("img","").data("img_id",0).addClass("post_success").keyup();setTimeout(function(){d.removeClass("post_success")},1500);$(".po_image .uiBox").remove();$(".precordGrid tr:eq(1)").after(j.data)}}})}return false}};$(".po_faces .OnTit").click(w);$(".iptFile").change(t);$(".po_video .OnTit").click(x);
$(".po_music .OnTit").click(y);$(".po_topic .OnTit").click(z);$(".postTimeBtn").click(function(){A.call(this)});$(".postNowBtn").click(function(){B.call(this)});$(".publish_textarea").bind("keyup",WBP.wordNum);$(".publish_textarea").bind("mouseup keyup",function(){WBP.cacheCur(this)});p.send_now=function(e,h){var b=$TAG("button",{cls:"uiBtnp mrs"}).html("<span>\u786e\u5b9a</span>"),c=$TAG("button",{cls:"uiBtng"}).html("<span>\u53d6\u6d88</span>"),d=$TAG("div",{cls:"pal clearfix"}).append($TAG("div",
{cls:"lfloat confirmIco mrs"}),$TAG("div",{cls:"fsl pvm"}).text("\u786e\u8ba4\u8981\u7acb\u5373\u53d1\u5e03\u5fae\u535a\u5417\uff1f"),$TAG("div",{cls:"hRight"}).append(b,c));b.click(function(){b.attr("disabled",true).addClass("uiBtnLoading");$.ajax({url:"/app/postAjax/sendnow",type:"POST",data:{id:h},dataType:"json",success:function(f){b.attr("disabled",false).removeClass("uiBtnLoading");if(parseInt(f.error))WBP.alertError(a,f.error_info);else{var g=$TAG("div",{cls:"pal"}).append($TAG("div",
{cls:"lfloat successIco mrs"}),$TAG("div",{cls:"fsl mvm"}).text("\u5fae\u535a\u53d1\u9001\u6210\u529f\uff01"));a.setBody(g);setTimeout(function(){a.close()},1E3);$(e).parents("tr").after(f.data).remove()}}})});c.click(function(){a.close()});var a=new SGJ.BOX({title:"\u7acb\u5373\u53d1\u5e03\uff1f",loading:false,body:d,mask:BOXMASK});a.bgiframe()};p.update_post=function(e,h){var b=new SGJ.BOX({width:540,mask:BOXMASK});b.bgiframe();$.ajax({url:"/app/postAjax/getrec",type:"POST",data:{id:h},dataType:"json",
success:function(c){function d(l){l=$TAG("div",{cls:"pal"}).append($TAG("div",{cls:"lfloat successIco mrs"}),$TAG("div",{cls:"fsl mvm"}).text(l));b.setBody(l);setTimeout(function(){b.close()},1E3)}var a=$(c.data),f=a.find(".po_faces .OnTit"),g=a.find(".iptFile"),i=a.find(".po_image"),j=a.find(".po_video .OnTit"),k=a.find(".po_music .OnTit"),n=a.find(".po_topic .OnTit"),q=a.find(".postTimeBtn"),r=a.find(".postNowBtn"),m=a.find(".publish_textarea");f.click(w);g.change(t);j.click(x);k.click(y);n.click(z);
q.click(function(){A.call(this,h,function(l){$(e).parents("tr").after(l.data).remove();d("\u4fee\u6539\u5fae\u535a\u6210\u529f\uff01")})});r.click(function(){b.close()});m.bind("keyup",WBP.wordNum);m.bind("mouseup keyup",function(){WBP.cacheCur(this)});if(c.image_url){f=$TAG("a",{cls:"fcmb fsm mrs tinyico-del rfloat"}).text("\u5220\u9664").click(function(){s.remove();m.data("img","");m.data("img_id",0)});g=$TAG("img",{cls:"clear"}).attr("src",c.image_url).width(120);j=$TAG("div",{cls:"mask"});k=$TAG("div",{cls:"uiBoxArrow"});
f=$TAG("div",{cls:"uiBoxContent hCent clearfix"}).append(j,k,f,g);f=$TAG("div",{cls:"uiBoxContainer"}).append(f);var s=$TAG("div",{cls:"uiBox"}).append(f).css({width:143});i.append(s)}m.data("img",c.image_url);m.data("img_id",c.image_id);b.setTitle("\u4fee\u6539\u5fae\u535a");b.setBody($TAG("div",{cls:"pvm"}).append(a));m.keyup().focus()}})};p.del_posted_status_ajax=function(e,h){var b=$TAG("button",{cls:"uiBtnp mrs"}).html("<span>\u786e\u5b9a</span>"),c=$TAG("button",{cls:"uiBtng"}).html("<span>\u53d6\u6d88</span>"),d=$TAG("div",
{cls:"pal clearfix"}).append($TAG("div",{cls:"lfloat confirmIco mrs"}),$TAG("div",{cls:"fsl pvm"}).text("\u786e\u8ba4\u5220\u9664\u5fae\u535a\u5417\uff1f"),$TAG("div",{cls:"hRight"}).append(b,c));b.click(function(){b.attr("disabled",true).addClass("uiBtnLoading");$.ajax({url:"/app/postAjax/delweibo",type:"POST",data:{id:h},dataType:"json",success:function(f){b.attr("disabled",false).removeClass("uiBtnLoading");if(parseInt(f.error))WBP.alertError(a,f.error_info);else{$(e).parents("tr").remove();
a.close()}}})});c.click(function(){a.close()});var a=new SGJ.BOX({title:"\u5220\u9664\u5fae\u535a\uff1f",loading:false,body:d,mask:BOXMASK});a.bgiframe()};p.del_post=function(e,h){var b=$TAG("button",{cls:"uiBtnp mrs"}).html("<span>\u786e\u5b9a</span>"),c=$TAG("button",{cls:"uiBtng"}).html("<span>\u53d6\u6d88</span>"),d=$TAG("div",{cls:"pal clearfix"}).append($TAG("div",{cls:"lfloat confirmIco mrs"}),$TAG("div",{cls:"fsl pvm"}).text("\u786e\u8ba4\u5220\u9664\u8fd9\u6761\u8bb0\u5f55\u5417\uff1f"),
$TAG("div",{cls:"hRight"}).append(b,c));b.click(function(){b.attr("disabled",true).addClass("uiBtnLoading");$.ajax({url:"/app/postAjax/delete",type:"POST",data:{id:h},dataType:"json",success:function(f){b.attr("disabled",false).removeClass("uiBtnLoading");if(parseInt(f.error))WBP.alertError(a,f.error_info);else{$(e).parents("tr").remove();a.close()}}})});c.click(function(){a.close()});var a=new SGJ.BOX({title:"\u5220\u9664\u8bb0\u5f55\uff1f",loading:false,body:d,mask:BOXMASK});a.bgiframe()};
p.update_rt_post=function(e,h){var b=new SGJ.BOX({width:450,loading:true,mask:BOXMASK});$.ajax({url:"/app/rt/getrec",type:"POST",dataType:"json",data:{id:h},success:function(c){if(parseInt(c.error))WBP.alertError(b,c.error_info);else{var d=c.rt_info,a=c.data,f=$('<div class="wordNumBg"><div class="surplus">\u4f60\u8fd8\u53ef\u4ee5\u8f93\u5165<span class="pipsLim">140</span>\u5b57</div><div class="over">\u5df2\u8d85\u51fa<span class="pipsLim">0</span>\u5b57</div></div>'),g=$TAG("textarea",{cls:"boxtextarea"}).attr("name",
"content").bind("keyup",WBP.wordNum).val(a.content);c=$('<a title="\u8868\u60c5" class="faceicon1" ></a>').click(function(){App.showFaces(this,g[0],-29,$(window).scrollTop()+5)});var i=$TAG("button",{cls:"uiBtnp mrs"}).html("<span>\u5b9a\u65f6\u8f6c\u53d1</span>"),j=$TAG("button",{cls:"uiBtng"}).attr("type","button").html("<span>\u53d6\u6d88</span>");a=new Date(a.schedule_time.replace(/-/g,"/"));var k=$('<input type="text" autocomplete="off" onfocus="WdatePicker({dateFmt:\'yyyy-MM-dd\',minDate:\'%y-%M-%d\'})" class="hasDatepicker mrs" name="schedule_ymd" value="" id="pickdater_0" readonly="">').val(C(a)),
n=[];$.each(v(0,23),function(l,o){n.push('<option value="'+o+'">'+o+"</option>")});var q=a.getHours().toString(),r=$('<select autocomplete="off" name="schedule_hour">'+n.join("")+"</select>").val(q),m=[];$.each(v(0,59),function(l,o){m.push('<option value="'+o+'">'+o+"</option>")});a=a.getMinutes().toString();var s=$('<select autocomplete="off" name="schedule_minute">'+m.join("")+"</select>").val(a.length==1?"0"+a:a);i.click(function(){if(g.val()==""||f.hasClass("wordNumOver")){g.focus();WBP.noticeInput(g[0]);
return false}i.attr("disabled",true).addClass("uiBtnLoading");$.ajax({url:"/app/postAjax/rtupd",type:"POST",data:{id:h,content:g.val(),schedule_ymd:k.val(),schedule_hour:r.val(),schedule_minute:s.val()},dataType:"json",success:function(l){if(parseInt(l.error))WBP.alertError(b,l.error_info);else{var o=$TAG("div",{cls:"pal clearfix"}).append($TAG("div",{cls:"lfloat successIco mrs"}),$TAG("div",{cls:"fsl pvm"}).text("\u5b9a\u65f6\u8f6c\u53d1\u8bbe\u7f6e\u6210\u529f\uff01"));b.setBody(o);setTimeout(function(){b.close()},
1E3);$(e).parents("tr").after(l.data).remove()}}});return false});j.click(function(){b.close()});d=$TAG("div",{cls:"pam"}).append($TAG("div",{cls:"pas mbm"}).append($TAG("a").append("@"+d.user_info.screen_name),"\uff1a",d.text).css("background","#F8F8F8"),$TAG("div",{cls:"clearfix mbs"}).append($TAG("div",{cls:"lfloat"}).append(c),$TAG("div",{cls:"rfloat relayNum"}).append(f)),g,$TAG("div",{cls:"date mvs"}).append("\u5b9a\u65f6\u8f6c\u53d1\u65f6\u95f4\uff1a",k,r," : ",s),$TAG("div",{cls:"hRight"}).append(i,
j));b.setTitle("\u4fee\u6539\u5b9a\u65f6\u8f6c\u53d1");b.setBody(d);g.keyup().focus();WBP.setSelectText(g[0],0,0)}}})};p.send_rt_now=function(e,h){var b=$TAG("button",{cls:"uiBtnp mrs"}).html("<span>\u786e\u5b9a</span>"),c=$TAG("button",{cls:"uiBtng"}).html("<span>\u53d6\u6d88</span>"),d=$TAG("div",{cls:"pal clearfix"}).append($TAG("div",{cls:"lfloat confirmIco mrs"}),$TAG("div",{cls:"fsl pvm"}).text("\u786e\u8ba4\u8981\u7acb\u5373\u8f6c\u53d1\u5fae\u535a\u5417\uff1f"),$TAG("div",{cls:"hRight"}).append(b,
c));b.click(function(){b.attr("disabled",true).addClass("uiBtnLoading");$.ajax({url:"/app/postAjax/rtnow",type:"POST",data:{id:h},dataType:"json",success:function(f){b.attr("disabled",false).removeClass("uiBtnLoading");if(parseInt(f.error))WBP.alertError(a,f.error_info);else{var g=$TAG("div",{cls:"pal"}).append($TAG("div",{cls:"lfloat successIco mrs"}),$TAG("div",{cls:"fsl mvm"}).text("\u5fae\u535a\u53d1\u9001\u6210\u529f\uff01"));a.setBody(g);setTimeout(function(){a.close()},1E3);
$(e).parents("tr").after(f.data).remove()}}})});c.click(function(){a.close()});var a=new SGJ.BOX({title:"\u7acb\u5373\u8f6c\u53d1\uff1f",loading:false,body:d,mask:BOXMASK})}});
